### ISSUE TITLE
easier system to publish new version

### ISSUE THREAD

**Issue by mh-cbon** [passbolt/passbolt_madjs#1]
hi,

just a quick note to suggest a small improvements on the system to publish a new version, instead of doing by hand, you may use npm scripts, such : 

```js
  "scripts": {
    "test": "exit 1",
    "patch": "npm version patch -m \"patch %s\"",
    "minor": "npm version minor -m \"minor %s\"",
    "major": "npm version major -m \"major %s\"",
    "preversion": "echo \"npm test: not defined\"",
    "version": "echo \"npm run build: not defined\"",
    "postversion": "git push && git push --tags && npm run public",
    "public": "npm publish"
  },
```

Then you can run,
`npm run patch|mior|major`

Which will effectively update the package version field, git commit, git tag, npm release accordingly.
If you d set the test script appropriately and update the preversion it would run the test before a release.
version script should be used to build the files.

read more about that here https://docs.npmjs.com/cli/version and I actively use this pattern so you know where to give a look t its results.

cheers

**Comment by kevinmuller** [comment]
Hi @mh-cbon 
A big thanks for the tip. Indeed it simplifies the whole procedure. We are going to implement it for the next release.
Cheers.
